version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U umami" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - umami-network

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:password@postgres:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: secret
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/api/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - umami-network

networks:
  umami-network:
    driver: bridge

volumes:
  postgres_data: